"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2

# main-background: #4C566A
# main foreground: #D8DEE9

# LEFT
[[blocks]]
alignment = "left"
type = "prompt"
# Dir
[[blocks.segments]]
background = "#4C566A"
foreground = "#D8DEE9"
style = "diamond"
leading_diamond = ""
template = " {{.Folder}} "
type = "path"

# Git
[[blocks.segments]]
background = "#A3BE8C"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#BF616A{{ end }}",
  "{{ if gt .Ahead 0 }}#B48EAD{{ end }}",
  "{{ if gt .Behind 0 }}#B48EAD{{ end }}",
]
foreground = "#D8DEE9"
powerline_symbol = ""
style = "powerline"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
type = "git"

[blocks.segments.properties]
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
background = "#4C566A"
background_templates = ["{{ if gt .Code 0 }}#BF616A{{ end }}"]
foreground = "#D8DEE9"
#   leading_diamond = "<transparent,background></>"
style = "diamond"
template = "  {{ if gt .Code 0 }} {{ .Meaning }}{{ else }}{{ end }} "
trailing_diamond = ""
type = "exit"


[blocks.segments.properties]
always_enabled = true
# ----------------------------------------------------------------
# RIGHT
[[blocks]]
alignment = "right"
type = "prompt"
# SHELL
[[blocks.segments]]
background = "#4C566A"
foreground = "#D8DEE9"
style = "plain"
template = "<#4C566A,transparent></>  {{ .Name }} <#4C566A,#4C566A></>"
type = "shell"
# --------------------
# ExecutionTime
[[blocks.segments]]
type = "executiontime"
style = "diamond"
background = "#4C566A"
foreground = "#D8DEE9"
template = "<#4C566A,transparent></> {{ .FormattedMs }} "
trailing_diamond = ""
[blocks.segments.properties]
threshold = 20
style = "amarillo"
always_enabled = true

# ----------------------------------------------------------------
# EXTRAS 
[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
background = "#4C566A"
foreground = "#D8DEE9"
leading_diamond = "<transparent,background></>"
style = "diamond"
template = " ﴱ Kubernetes {{.Context}} cluster {{if .Namespace}}- {{.Namespace}} namespace{{end}} "
trailing_diamond = ""
type = "kubectl"

[[blocks.segments]]
background = "#9ec3f0"
foreground = "#D8DEE9"
powerline_symbol = ""
style = "powerline"
template = ' ﴃ Subscription {{ .Name }} ({{ if .EnvironmentName | contains "AzureCloud" }}{{ "Global" }}{{ else }}{{ .EnvironmentName }}{{ end }}) '
type = "az"
# -----------------------------------------------------------------
# PROMPT
[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#D8DEE9"
style = "plain"
template = " $ "
type = "text"
# ------------------------
